// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

package com.gulden.jniunifiedbackend;

/** This interface will be implemented in Java and ObjC and can be called from C++. */
public abstract class GuldenUnifiedFrontend {
    public abstract boolean notifySPVProgress(int startHeight, int progessHeight, int expectedHeight);

    public abstract boolean notifyBalanceChange(BalanceRecord newBalance);

    public abstract boolean notifyNewTransaction(TransactionRecord newTransaction);

    public abstract void notifyInitWithExistingWallet();

    public abstract void notifyInitWithoutExistingWallet();

    public abstract boolean notifyShutdown();

    public abstract boolean notifyCoreReady();

    public abstract void logPrint(String str);
}
