// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

package com.gulden.jniunifiedbackend;

/** This interface will be implemented in Java and ObjC and can be called from C++. */
public abstract class GuldenUnifiedFrontend {
    /**
     * Fraction of work done since session start or last progress reset [0..1]
     * Unified progress combines connection state, header and block sync
     */
    public abstract void notifyUnifiedProgress(float progress);

    public abstract boolean notifyBalanceChange(BalanceRecord newBalance);

    /**
     * Notification of new mutations.
     * If selfCommitted it is due to a call to performPaymentToRecipient, else it is because of a transaction
     * reached us in another way. In general this will be because we received funds from someone, hower there are
     * also cases where funds is send from our wallet while !selfCommitted (for example by a linked desktop wallet
     * or another wallet instance using the same keys as ours).
     */
    public abstract void notifyNewMutation(MutationRecord mutation, boolean selfCommitted);

    public abstract boolean notifyUpdatedTransaction(TransactionRecord transaction);

    public abstract void notifyInitWithExistingWallet();

    public abstract void notifyInitWithoutExistingWallet();

    public abstract boolean notifyShutdown();

    public abstract boolean notifyCoreReady();

    public abstract void logPrint(String str);
}
