// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

package com.gulden.jniunifiedbackend;

public final class MnemonicRecord {


    /*package*/ final String mPhraseWithBirthNumber;

    /*package*/ final String mPhrase;

    /*package*/ final long mBirthNumber;

    public MnemonicRecord(
            String phraseWithBirthNumber,
            String phrase,
            long birthNumber) {
        this.mPhraseWithBirthNumber = phraseWithBirthNumber;
        this.mPhrase = phrase;
        this.mBirthNumber = birthNumber;
    }

    public String getPhraseWithBirthNumber() {
        return mPhraseWithBirthNumber;
    }

    public String getPhrase() {
        return mPhrase;
    }

    public long getBirthNumber() {
        return mBirthNumber;
    }

    @Override
    public String toString() {
        return "MnemonicRecord{" +
                "mPhraseWithBirthNumber=" + mPhraseWithBirthNumber +
                "," + "mPhrase=" + mPhrase +
                "," + "mBirthNumber=" + mBirthNumber +
        "}";
    }

}
