// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import <Foundation/Foundation.h>

/**Data record representing a link between an account and an external service (e.g. Holdin.com) */
@interface DBAccountLinkRecord : NSObject
- (nonnull instancetype)initWithServiceName:(nonnull NSString *)serviceName
                                serviceData:(nonnull NSString *)serviceData;
+ (nonnull instancetype)accountLinkRecordWithServiceName:(nonnull NSString *)serviceName
                                             serviceData:(nonnull NSString *)serviceData;

/** What service is it (each service should use a unique string to identify itself)  */
@property (nonatomic, readonly, nonnull) NSString * serviceName;

/** Any data unique to the service, e.g. a key used for secure communication or similar */
@property (nonatomic, readonly, nonnull) NSString * serviceData;

@end
