// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import <Foundation/Foundation.h>

@interface DBAccountRecord : NSObject
- (nonnull instancetype)initWithUUID:(nonnull NSString *)UUID
                               label:(nonnull NSString *)label
                               state:(nonnull NSString *)state
                                type:(nonnull NSString *)type
                                isHD:(BOOL)isHD;
+ (nonnull instancetype)accountRecordWithUUID:(nonnull NSString *)UUID
                                        label:(nonnull NSString *)label
                                        state:(nonnull NSString *)state
                                         type:(nonnull NSString *)type
                                         isHD:(BOOL)isHD;

@property (nonatomic, readonly, nonnull) NSString * UUID;

@property (nonatomic, readonly, nonnull) NSString * label;

@property (nonatomic, readonly, nonnull) NSString * state;

@property (nonatomic, readonly, nonnull) NSString * type;

/**Is this account 'HD' (i.e. part of what can be recovered from a recovery phrase) */
@property (nonatomic, readonly) BOOL isHD;

@end
