// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import "DBBalanceRecord.h"
#include "balance_record.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBBalanceRecord;

namespace djinni_generated {

struct BalanceRecord
{
    using CppType = ::BalanceRecord;
    using ObjcType = DBBalanceRecord*;

    using Boxed = BalanceRecord;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
