// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import "DBBlockInfoRecord+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto BlockInfoRecord::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.height),
            ::djinni::I64::toCpp(obj.timeStamp),
            ::djinni::String::toCpp(obj.blockHash)};
}

auto BlockInfoRecord::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBBlockInfoRecord alloc] initWithHeight:(::djinni::I32::fromCpp(cpp.height))
                                           timeStamp:(::djinni::I64::fromCpp(cpp.timeStamp))
                                           blockHash:(::djinni::String::fromCpp(cpp.blockHash))];
}

}  // namespace djinni_generated
