// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import <Foundation/Foundation.h>

@interface DBBlockInfoRecord : NSObject
- (nonnull instancetype)initWithHeight:(int32_t)height
                             timeStamp:(int64_t)timeStamp
                             blockHash:(nonnull NSString *)blockHash;
+ (nonnull instancetype)blockInfoRecordWithHeight:(int32_t)height
                                        timeStamp:(int64_t)timeStamp
                                        blockHash:(nonnull NSString *)blockHash;

@property (nonatomic, readonly) int32_t height;

@property (nonatomic, readonly) int64_t timeStamp;

@property (nonatomic, readonly, nonnull) NSString * blockHash;

@end
