// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import "DBBlockinfoRecord+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto BlockinfoRecord::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.height),
            ::djinni::I64::toCpp(obj.timestamp),
            ::djinni::String::toCpp(obj.blockhash)};
}

auto BlockinfoRecord::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBBlockinfoRecord alloc] initWithHeight:(::djinni::I32::fromCpp(cpp.height))
                                           timestamp:(::djinni::I64::fromCpp(cpp.timestamp))
                                           blockhash:(::djinni::String::fromCpp(cpp.blockhash))];
}

}  // namespace djinni_generated
