// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import <Foundation/Foundation.h>

@interface DBBlockinfoRecord : NSObject
- (nonnull instancetype)initWithHeight:(int32_t)height
                             timestamp:(int64_t)timestamp
                             blockhash:(nonnull NSString *)blockhash;
+ (nonnull instancetype)blockinfoRecordWithHeight:(int32_t)height
                                        timestamp:(int64_t)timestamp
                                        blockhash:(nonnull NSString *)blockhash;

@property (nonatomic, readonly) int32_t height;

@property (nonatomic, readonly) int64_t timestamp;

@property (nonatomic, readonly, nonnull) NSString * blockhash;

@end
