// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import "DBBlockinfoRecord.h"


@implementation DBBlockinfoRecord

- (nonnull instancetype)initWithHeight:(int32_t)height
                             timestamp:(int64_t)timestamp
                             blockhash:(nonnull NSString *)blockhash
{
    if (self = [super init]) {
        _height = height;
        _timestamp = timestamp;
        _blockhash = [blockhash copy];
    }
    return self;
}

+ (nonnull instancetype)blockinfoRecordWithHeight:(int32_t)height
                                        timestamp:(int64_t)timestamp
                                        blockhash:(nonnull NSString *)blockhash
{
    return [[self alloc] initWithHeight:height
                              timestamp:timestamp
                              blockhash:blockhash];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p height:%@ timestamp:%@ blockhash:%@>", self.class, (void *)self, @(self.height), @(self.timestamp), self.blockhash];
}

@end
