// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import "DBBlockinfoRecord.h"
#include "blockinfo_record.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBBlockinfoRecord;

namespace djinni_generated {

struct BlockinfoRecord
{
    using CppType = ::BlockinfoRecord;
    using ObjcType = DBBlockinfoRecord*;

    using Boxed = BlockinfoRecord;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
