// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import "DBGuldenUnifiedFrontend+Private.h"
#import "DBGuldenUnifiedFrontend.h"
#import "DBBalanceRecord+Private.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class GuldenUnifiedFrontend::ObjcProxy final
: public ::GuldenUnifiedFrontend
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::GuldenUnifiedFrontend;
public:
    using ObjcProxyBase::ObjcProxyBase;
    bool notifySPVProgress(int32_t c_start_height, int32_t c_progess_height, int32_t c_expected_height) override
    {
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() notifySPVProgress:(::djinni::I32::fromCpp(c_start_height))
                                                                                progessHeight:(::djinni::I32::fromCpp(c_progess_height))
                                                                               expectedHeight:(::djinni::I32::fromCpp(c_expected_height))];
            return ::djinni::Bool::toCpp(objcpp_result_);
        }
    }
    bool notifyBalanceChange(const ::BalanceRecord & c_new_balance) override
    {
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() notifyBalanceChange:(::djinni_generated::BalanceRecord::fromCpp(c_new_balance))];
            return ::djinni::Bool::toCpp(objcpp_result_);
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto GuldenUnifiedFrontend::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto GuldenUnifiedFrontend::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

}  // namespace djinni_generated
