// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import <Foundation/Foundation.h>


/** Monitoring events */
@protocol DBGuldenMonitorListener

- (void)onPartialChain:(int32_t)height
        probableHeight:(int32_t)probableHeight
                offset:(int32_t)offset;

- (void)onPruned:(int32_t)height;

- (void)onProcessedSPVBlocks:(int32_t)height;

@end
