// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#include "i_generation_listener.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol DBIGenerationListener;

namespace djinni_generated {

class IGenerationListener
{
public:
    using CppType = std::shared_ptr<::IGenerationListener>;
    using CppOptType = std::shared_ptr<::IGenerationListener>;
    using ObjcType = id<DBIGenerationListener>;

    using Boxed = IGenerationListener;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

