// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import <Foundation/Foundation.h>


/** Interface to receive updates about block generation */
@protocol DBIGenerationListener

/** Signal that block generation has started */
- (void)onGenerationStarted;

/** Signal that block generation has stopped */
- (void)onGenerationStopped;

/** Periodically signal latest block generation statistics */
- (void)onStatsUpdated:(double)hashesPerSecond
   hashesPerSecondUnit:(nonnull NSString *)hashesPerSecondUnit
rollingHashesPerSecond:(double)rollingHashesPerSecond
rollingHashesPerSecondUnit:(nonnull NSString *)rollingHashesPerSecondUnit
   bestHashesPerSecond:(double)bestHashesPerSecond
bestHashesPerSecondUnit:(nonnull NSString *)bestHashesPerSecondUnit
        arenaSetupTime:(double)arenaSetupTime;

@end
