// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#include "i_generation_controller.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBIGenerationController;

namespace djinni_generated {

class IGenerationController
{
public:
    using CppType = std::shared_ptr<::IGenerationController>;
    using CppOptType = std::shared_ptr<::IGenerationController>;
    using ObjcType = DBIGenerationController*;

    using Boxed = IGenerationController;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

