// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import "DBIGenerationListener+Private.h"
#import "DBIGenerationListener.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class IGenerationListener::ObjcProxy final
: public ::IGenerationListener
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::IGenerationListener;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void onGenerationStarted() override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onGenerationStarted];
        }
    }
    void onGenerationStopped() override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onGenerationStopped];
        }
    }
    void onStatsUpdated(double c_hashesPerSecond, const std::string & c_hashesPerSecondUnit, double c_rollingHashesPerSecond, const std::string & c_rollingHashesPerSecondUnit, double c_bestHashesPerSecond, const std::string & c_bestHashesPerSecondUnit, double c_arenaSetupTime) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onStatsUpdated:(::djinni::F64::fromCpp(c_hashesPerSecond))
                                                 hashesPerSecondUnit:(::djinni::String::fromCpp(c_hashesPerSecondUnit))
                                              rollingHashesPerSecond:(::djinni::F64::fromCpp(c_rollingHashesPerSecond))
                                          rollingHashesPerSecondUnit:(::djinni::String::fromCpp(c_rollingHashesPerSecondUnit))
                                                 bestHashesPerSecond:(::djinni::F64::fromCpp(c_bestHashesPerSecond))
                                             bestHashesPerSecondUnit:(::djinni::String::fromCpp(c_bestHashesPerSecondUnit))
                                                      arenaSetupTime:(::djinni::F64::fromCpp(c_arenaSetupTime))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto IGenerationListener::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto IGenerationListener::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

}  // namespace djinni_generated
