// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import <Foundation/Foundation.h>
@protocol DBIGenerationListener;


/** C++ interface to control generation of blocks (proof of work) */
@interface DBIGenerationController : NSObject

/** Register listener to be notified of generation related events */
+ (void)setListener:(nullable id<DBIGenerationListener>)generationListener;

/**
 * Activate block generation (proof of work)
 * Number of threads should not exceed physical threads, memory limit is a string specifier in the form of #B/#K/#M/#G (e.g. 102400B, 10240K, 1024M, 1G)
 */
+ (BOOL)startGeneration:(int32_t)numThreads
            memoryLimit:(nonnull NSString *)memoryLimit;

/** Stop any active block generation (proof of work) */
+ (BOOL)stopGeneration;

@end
