// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#include "i_p2p_network_listener.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol DBIP2pNetworkListener;

namespace djinni_generated {

class IP2pNetworkListener
{
public:
    using CppType = std::shared_ptr<::IP2pNetworkListener>;
    using CppOptType = std::shared_ptr<::IP2pNetworkListener>;
    using ObjcType = id<DBIP2pNetworkListener>;

    using Boxed = IP2pNetworkListener;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

