// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#include "i_witness_controller.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBIWitnessController;

namespace djinni_generated {

class IWitnessController
{
public:
    using CppType = std::shared_ptr<::IWitnessController>;
    using CppOptType = std::shared_ptr<::IWitnessController>;
    using ObjcType = DBIWitnessController*;

    using Boxed = IWitnessController;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

