// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import "DBMnemonicRecord+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto MnemonicRecord::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.phraseWithBirthNumber),
            ::djinni::String::toCpp(obj.phrase),
            ::djinni::I64::toCpp(obj.birthNumber)};
}

auto MnemonicRecord::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBMnemonicRecord alloc] initWithPhraseWithBirthNumber:(::djinni::String::fromCpp(cpp.phrase_with_birth_number))
                                                            phrase:(::djinni::String::fromCpp(cpp.phrase))
                                                       birthNumber:(::djinni::I64::fromCpp(cpp.birth_number))];
}

}  // namespace djinni_generated
