// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#include "monitor_listener.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol DBMonitorListener;

namespace djinni_generated {

class MonitorListener
{
public:
    using CppType = std::shared_ptr<::MonitorListener>;
    using CppOptType = std::shared_ptr<::MonitorListener>;
    using ObjcType = id<DBMonitorListener>;

    using Boxed = MonitorListener;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

