// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import "DBMonitorRecord.h"
#include "monitor_record.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBMonitorRecord;

namespace djinni_generated {

struct MonitorRecord
{
    using CppType = ::MonitorRecord;
    using ObjcType = DBMonitorRecord*;

    using Boxed = MonitorRecord;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
