// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import "DBMutationRecord.h"


@implementation DBMutationRecord

- (nonnull instancetype)initWithChange:(int64_t)change
                                    tx:(nonnull DBTransactionRecord *)tx
{
    if (self = [super init]) {
        _change = change;
        _tx = tx;
    }
    return self;
}

+ (nonnull instancetype)mutationRecordWithChange:(int64_t)change
                                              tx:(nonnull DBTransactionRecord *)tx
{
    return [[self alloc] initWithChange:change
                                     tx:tx];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p change:%@ tx:%@>", self.class, (void *)self, @(self.change), self.tx];
}

@end
