// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import "DBMutationRecord+Private.h"
#import "DBTransactionRecord+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto MutationRecord::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I64::toCpp(obj.change),
            ::djinni_generated::TransactionRecord::toCpp(obj.tx)};
}

auto MutationRecord::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBMutationRecord alloc] initWithChange:(::djinni::I64::fromCpp(cpp.change))
                                                 tx:(::djinni_generated::TransactionRecord::fromCpp(cpp.tx))];
}

}  // namespace djinni_generated
