// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import "DBMutationRecord.h"
#include "mutation_record.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBMutationRecord;

namespace djinni_generated {

struct MutationRecord
{
    using CppType = ::MutationRecord;
    using ObjcType = DBMutationRecord*;

    using Boxed = MutationRecord;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
