// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import "DBTransactionStatus.h"
#import <Foundation/Foundation.h>

@interface DBMutationRecord : NSObject
- (nonnull instancetype)initWithChange:(int64_t)change
                             timestamp:(int64_t)timestamp
                                txHash:(nonnull NSString *)txHash
                    recipientAddresses:(nonnull NSString *)recipientAddresses
                                status:(DBTransactionStatus)status
                                 depth:(int32_t)depth;
+ (nonnull instancetype)mutationRecordWithChange:(int64_t)change
                                       timestamp:(int64_t)timestamp
                                          txHash:(nonnull NSString *)txHash
                              recipientAddresses:(nonnull NSString *)recipientAddresses
                                          status:(DBTransactionStatus)status
                                           depth:(int32_t)depth;

@property (nonatomic, readonly) int64_t change;

@property (nonatomic, readonly) int64_t timestamp;

@property (nonatomic, readonly, nonnull) NSString * txHash;

/** Address(es) of transaction recipient(s) (if transaction is sent by us then this excludes e.g. change and only has other wallets addresses) */
@property (nonatomic, readonly, nonnull) NSString * recipientAddresses;

@property (nonatomic, readonly) DBTransactionStatus status;

@property (nonatomic, readonly) int32_t depth;

@end
