// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import "DBOutputRecord+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto OutputRecord::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I64::toCpp(obj.amount),
            ::djinni::String::toCpp(obj.address),
            ::djinni::String::toCpp(obj.label)};
}

auto OutputRecord::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBOutputRecord alloc] initWithAmount:(::djinni::I64::fromCpp(cpp.amount))
                                          address:(::djinni::String::fromCpp(cpp.address))
                                            label:(::djinni::String::fromCpp(cpp.label))];
}

}  // namespace djinni_generated
