// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import "DBPeerRecord.h"


@implementation DBPeerRecord

- (nonnull instancetype)initWithIp:(nonnull NSString *)ip
                          hostname:(nonnull NSString *)hostname
                       startHeight:(int32_t)startHeight
                      syncedHeight:(int32_t)syncedHeight
                      commonHeight:(int32_t)commonHeight
                           latency:(int32_t)latency
                         userAgent:(nonnull NSString *)userAgent
                          protocol:(int64_t)protocol
{
    if (self = [super init]) {
        _ip = [ip copy];
        _hostname = [hostname copy];
        _startHeight = startHeight;
        _syncedHeight = syncedHeight;
        _commonHeight = commonHeight;
        _latency = latency;
        _userAgent = [userAgent copy];
        _protocol = protocol;
    }
    return self;
}

+ (nonnull instancetype)peerRecordWithIp:(nonnull NSString *)ip
                                hostname:(nonnull NSString *)hostname
                             startHeight:(int32_t)startHeight
                            syncedHeight:(int32_t)syncedHeight
                            commonHeight:(int32_t)commonHeight
                                 latency:(int32_t)latency
                               userAgent:(nonnull NSString *)userAgent
                                protocol:(int64_t)protocol
{
    return [[self alloc] initWithIp:ip
                           hostname:hostname
                        startHeight:startHeight
                       syncedHeight:syncedHeight
                       commonHeight:commonHeight
                            latency:latency
                          userAgent:userAgent
                           protocol:protocol];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p ip:%@ hostname:%@ startHeight:%@ syncedHeight:%@ commonHeight:%@ latency:%@ userAgent:%@ protocol:%@>", self.class, (void *)self, self.ip, self.hostname, @(self.startHeight), @(self.syncedHeight), @(self.commonHeight), @(self.latency), self.userAgent, @(self.protocol)];
}

@end
