// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import "DBPeerRecord.h"
#include "peer_record.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBPeerRecord;

namespace djinni_generated {

struct PeerRecord
{
    using CppType = ::PeerRecord;
    using ObjcType = DBPeerRecord*;

    using Boxed = PeerRecord;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
