// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import "DBResultRecord.h"
#include "result_record.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBResultRecord;

namespace djinni_generated {

struct ResultRecord
{
    using CppType = ::ResultRecord;
    using ObjcType = DBResultRecord*;

    using Boxed = ResultRecord;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
