// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import "DBResultRecord.h"


@implementation DBResultRecord

- (nonnull instancetype)initWithResult:(BOOL)result
                                  info:(nonnull NSString *)info
{
    if (self = [super init]) {
        _result = result;
        _info = [info copy];
    }
    return self;
}

+ (nonnull instancetype)resultRecordWithResult:(BOOL)result
                                          info:(nonnull NSString *)info
{
    return [(DBResultRecord*)[self alloc] initWithResult:result
                                                    info:info];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p result:%@ info:%@>", self.class, (void *)self, @(self.result), self.info];
}

@end
