// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import "DBTransactionRecord+Private.h"
#import "DBTransactionType+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto TransactionRecord::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Enum<::TransactionType, DBTransactionType>::toCpp(obj.type),
            ::djinni::I64::toCpp(obj.amount),
            ::djinni::String::toCpp(obj.address),
            ::djinni::String::toCpp(obj.label),
            ::djinni::I64::toCpp(obj.timestamp)};
}

auto TransactionRecord::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBTransactionRecord alloc] initWithType:(::djinni::Enum<::TransactionType, DBTransactionType>::fromCpp(cpp.type))
                                              amount:(::djinni::I64::fromCpp(cpp.amount))
                                             address:(::djinni::String::fromCpp(cpp.address))
                                               label:(::djinni::String::fromCpp(cpp.label))
                                           timestamp:(::djinni::I64::fromCpp(cpp.timestamp))];
}

}  // namespace djinni_generated
