// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import "DBTransactionRecord.h"


@implementation DBTransactionRecord

- (nonnull instancetype)initWithType:(DBTransactionType)type
                              amount:(int64_t)amount
                             address:(nonnull NSString *)address
                               label:(nonnull NSString *)label
                           timestamp:(int64_t)timestamp
{
    if (self = [super init]) {
        _type = type;
        _amount = amount;
        _address = [address copy];
        _label = [label copy];
        _timestamp = timestamp;
    }
    return self;
}

+ (nonnull instancetype)transactionRecordWithType:(DBTransactionType)type
                                           amount:(int64_t)amount
                                          address:(nonnull NSString *)address
                                            label:(nonnull NSString *)label
                                        timestamp:(int64_t)timestamp
{
    return [[self alloc] initWithType:type
                               amount:amount
                              address:address
                                label:label
                            timestamp:timestamp];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p type:%@ amount:%@ address:%@ label:%@ timestamp:%@>", self.class, (void *)self, @(self.type), @(self.amount), self.address, self.label, @(self.timestamp)];
}

@end
