// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import "DBTransactionRecord+Private.h"
#import "DBOutputRecord+Private.h"
#import "DBTransactionStatus+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto TransactionRecord::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.txHash),
            ::djinni::I64::toCpp(obj.timestamp),
            ::djinni::I64::toCpp(obj.amount),
            ::djinni::I64::toCpp(obj.fee),
            ::djinni::Enum<::TransactionStatus, DBTransactionStatus>::toCpp(obj.status),
            ::djinni::I32::toCpp(obj.height),
            ::djinni::I64::toCpp(obj.blocktime),
            ::djinni::I32::toCpp(obj.depth),
            ::djinni::List<::djinni_generated::OutputRecord>::toCpp(obj.receivedOutputs),
            ::djinni::List<::djinni_generated::OutputRecord>::toCpp(obj.sentOutputs)};
}

auto TransactionRecord::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBTransactionRecord alloc] initWithTxHash:(::djinni::String::fromCpp(cpp.txHash))
                                             timestamp:(::djinni::I64::fromCpp(cpp.timestamp))
                                                amount:(::djinni::I64::fromCpp(cpp.amount))
                                                   fee:(::djinni::I64::fromCpp(cpp.fee))
                                                status:(::djinni::Enum<::TransactionStatus, DBTransactionStatus>::fromCpp(cpp.status))
                                                height:(::djinni::I32::fromCpp(cpp.height))
                                             blocktime:(::djinni::I64::fromCpp(cpp.blocktime))
                                                 depth:(::djinni::I32::fromCpp(cpp.depth))
                                       receivedOutputs:(::djinni::List<::djinni_generated::OutputRecord>::fromCpp(cpp.receivedOutputs))
                                           sentOutputs:(::djinni::List<::djinni_generated::OutputRecord>::fromCpp(cpp.sentOutputs))];
}

}  // namespace djinni_generated
