// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import "DBUriRecord.h"
#include "uri_record.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBUriRecord;

namespace djinni_generated {

struct UriRecord
{
    using CppType = ::UriRecord;
    using ObjcType = DBUriRecord*;

    using Boxed = UriRecord;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
