// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import "DBWalletLockStatus+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto WalletLockStatus::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Bool::toCpp(obj.locked),
            ::djinni::I64::toCpp(obj.lockTimeout)};
}

auto WalletLockStatus::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBWalletLockStatus alloc] initWithLocked:(::djinni::Bool::fromCpp(cpp.locked))
                                          lockTimeout:(::djinni::I64::fromCpp(cpp.lock_timeout))];
}

}  // namespace djinni_generated
