// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import "DBWitnessEstimateInfoRecord.h"
#include "witness_estimate_info_record.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DBWitnessEstimateInfoRecord;

namespace djinni_generated {

struct WitnessEstimateInfoRecord
{
    using CppType = ::WitnessEstimateInfoRecord;
    using ObjcType = DBWitnessEstimateInfoRecord*;

    using Boxed = WitnessEstimateInfoRecord;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
