// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import "DBWitnessFundingResultRecord+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto WitnessFundingResultRecord::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.status),
            ::djinni::String::toCpp(obj.txid),
            ::djinni::I64::toCpp(obj.fee)};
}

auto WitnessFundingResultRecord::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBWitnessFundingResultRecord alloc] initWithStatus:(::djinni::String::fromCpp(cpp.status))
                                                           txid:(::djinni::String::fromCpp(cpp.txid))
                                                            fee:(::djinni::I64::fromCpp(cpp.fee))];
}

}  // namespace djinni_generated
