// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import "DBWitnessEstimateInfoRecord+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto WitnessEstimateInfoRecord::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I64::toCpp(obj.networkWeight),
            ::djinni::I64::toCpp(obj.weight),
            ::djinni::I64::toCpp(obj.parts),
            ::djinni::F64::toCpp(obj.estimatedWitnessProbability),
            ::djinni::F64::toCpp(obj.estimatedBlocksPerDay),
            ::djinni::I64::toCpp(obj.estimatedDailyEarnings),
            ::djinni::I64::toCpp(obj.estimatedLifetimeEarnings)};
}

auto WitnessEstimateInfoRecord::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[DBWitnessEstimateInfoRecord alloc] initWithNetworkWeight:(::djinni::I64::fromCpp(cpp.network_weight))
                                                               weight:(::djinni::I64::fromCpp(cpp.weight))
                                                                parts:(::djinni::I64::fromCpp(cpp.parts))
                                          estimatedWitnessProbability:(::djinni::F64::fromCpp(cpp.estimated_witness_probability))
                                                estimatedBlocksPerDay:(::djinni::F64::fromCpp(cpp.estimated_blocks_per_day))
                                               estimatedDailyEarnings:(::djinni::I64::fromCpp(cpp.estimated_daily_earnings))
                                            estimatedLifetimeEarnings:(::djinni::I64::fromCpp(cpp.estimated_lifetime_earnings))];
}

}  // namespace djinni_generated
