// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import <Foundation/Foundation.h>

@interface DBWitnessFundingResultRecord : NSObject
- (nonnull instancetype)initWithStatus:(nonnull NSString *)status
                                  txid:(nonnull NSString *)txid
                                   fee:(int64_t)fee;
+ (nonnull instancetype)witnessFundingResultRecordWithStatus:(nonnull NSString *)status
                                                        txid:(nonnull NSString *)txid
                                                         fee:(int64_t)fee;

/** "success" on success, otherwise an error message */
@property (nonatomic, readonly, nonnull) NSString * status;

/** txid of the funding transaction, empty on failure */
@property (nonatomic, readonly, nonnull) NSString * txid;

/** fee charged by the transaction, 0 on failure */
@property (nonatomic, readonly) int64_t fee;

@end
