// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#import <Foundation/Foundation.h>

@interface DBWitnessAccountStatisticsRecord : NSObject
- (nonnull instancetype)initWithRequestStatus:(nonnull NSString *)requestStatus
                                accountStatus:(nonnull NSString *)accountStatus
                                accountWeight:(int64_t)accountWeight
                          accountAmountLocked:(int64_t)accountAmountLocked
                      accountWeightAtCreation:(int64_t)accountWeightAtCreation
                        networkTipTotalWeight:(int64_t)networkTipTotalWeight
      networkTotalWeightAtAccountCreationTime:(int64_t)networkTotalWeightAtAccountCreationTime
             accountInitialLockPeriodInBlocks:(int64_t)accountInitialLockPeriodInBlocks
           accountRemainingLockPeriodInBlocks:(int64_t)accountRemainingLockPeriodInBlocks
         accountExpectedWitnessPeriodInBlocks:(int64_t)accountExpectedWitnessPeriodInBlocks
        accountEstimatedWitnessPeriodInBlocks:(int64_t)accountEstimatedWitnessPeriodInBlocks
        accountInitialLockCreationBlockHeight:(int64_t)accountInitialLockCreationBlockHeight
                         accountIsCompounding:(BOOL)accountIsCompounding;
+ (nonnull instancetype)witnessAccountStatisticsRecordWithRequestStatus:(nonnull NSString *)requestStatus
                                                          accountStatus:(nonnull NSString *)accountStatus
                                                          accountWeight:(int64_t)accountWeight
                                                    accountAmountLocked:(int64_t)accountAmountLocked
                                                accountWeightAtCreation:(int64_t)accountWeightAtCreation
                                                  networkTipTotalWeight:(int64_t)networkTipTotalWeight
                                networkTotalWeightAtAccountCreationTime:(int64_t)networkTotalWeightAtAccountCreationTime
                                       accountInitialLockPeriodInBlocks:(int64_t)accountInitialLockPeriodInBlocks
                                     accountRemainingLockPeriodInBlocks:(int64_t)accountRemainingLockPeriodInBlocks
                                   accountExpectedWitnessPeriodInBlocks:(int64_t)accountExpectedWitnessPeriodInBlocks
                                  accountEstimatedWitnessPeriodInBlocks:(int64_t)accountEstimatedWitnessPeriodInBlocks
                                  accountInitialLockCreationBlockHeight:(int64_t)accountInitialLockCreationBlockHeight
                                                   accountIsCompounding:(BOOL)accountIsCompounding;

/** Success if request succeeded, otherwise an error message */
@property (nonatomic, readonly, nonnull) NSString * requestStatus;

/** Current state of the witness account, one of: "empty", "empty_with_remainder", "pending", "witnessing", "ended", "expired", "emptying" */
@property (nonatomic, readonly, nonnull) NSString * accountStatus;

/** Account weight */
@property (nonatomic, readonly) int64_t accountWeight;

/** Account amount locked */
@property (nonatomic, readonly) int64_t accountAmountLocked;

/** Account weight when it was created */
@property (nonatomic, readonly) int64_t accountWeightAtCreation;

/** Current network weight */
@property (nonatomic, readonly) int64_t networkTipTotalWeight;

/** Network weight when account was created */
@property (nonatomic, readonly) int64_t networkTotalWeightAtAccountCreationTime;

/** Account total lock period in blocks (from creation block) */
@property (nonatomic, readonly) int64_t accountInitialLockPeriodInBlocks;

/** Account remaining lock period in blocks (from chain tip) */
@property (nonatomic, readonly) int64_t accountRemainingLockPeriodInBlocks;

/** How often the account is "expected" by the network to witness in order to not be kicked off */
@property (nonatomic, readonly) int64_t accountExpectedWitnessPeriodInBlocks;

/** How often the account is estimated to witness */
@property (nonatomic, readonly) int64_t accountEstimatedWitnessPeriodInBlocks;

/** Height at which the account lock first entered the chain */
@property (nonatomic, readonly) int64_t accountInitialLockCreationBlockHeight;

/** Is this account currently set to compound */
@property (nonatomic, readonly) BOOL accountIsCompounding;

@end
