// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#pragma once

#include "djinni_support.hpp"
#include "qrcode_record.hpp"

namespace djinni_generated {

class NativeQrcodeRecord final {
public:
    using CppType = ::QrcodeRecord;
    using JniType = jobject;

    using Boxed = NativeQrcodeRecord;

    ~NativeQrcodeRecord();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeQrcodeRecord();
    friend ::djinni::JniClass<NativeQrcodeRecord>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/gulden/jniunifiedbackend/QrcodeRecord") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(I[B)V") };
    const jfieldID field_mWidth { ::djinni::jniGetFieldID(clazz.get(), "mWidth", "I") };
    const jfieldID field_mPixelData { ::djinni::jniGetFieldID(clazz.get(), "mPixelData", "[B") };
};

}  // namespace djinni_generated
