// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#pragma once

#include "djinni_support.hpp"
#include "result_record.hpp"

namespace djinni_generated {

class NativeResultRecord final {
public:
    using CppType = ::ResultRecord;
    using JniType = jobject;

    using Boxed = NativeResultRecord;

    ~NativeResultRecord();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeResultRecord();
    friend ::djinni::JniClass<NativeResultRecord>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("unity_wallet/jniunifiedbackend/ResultRecord") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(ZLjava/lang/String;)V") };
    const jfieldID field_mResult { ::djinni::jniGetFieldID(clazz.get(), "mResult", "Z") };
    const jfieldID field_mInfo { ::djinni::jniGetFieldID(clazz.get(), "mInfo", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
