// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#pragma once

#include "djinni_support.hpp"
#include "transaction_record.hpp"

namespace djinni_generated {

class NativeTransactionRecord final {
public:
    using CppType = ::TransactionRecord;
    using JniType = jobject;

    using Boxed = NativeTransactionRecord;

    ~NativeTransactionRecord();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeTransactionRecord();
    friend ::djinni::JniClass<NativeTransactionRecord>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/gulden/jniunifiedbackend/TransactionRecord") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;JJJLcom/gulden/jniunifiedbackend/TransactionStatus;IJILjava/util/ArrayList;Ljava/util/ArrayList;)V") };
    const jfieldID field_mTxHash { ::djinni::jniGetFieldID(clazz.get(), "mTxHash", "Ljava/lang/String;") };
    const jfieldID field_mTimeStamp { ::djinni::jniGetFieldID(clazz.get(), "mTimeStamp", "J") };
    const jfieldID field_mAmount { ::djinni::jniGetFieldID(clazz.get(), "mAmount", "J") };
    const jfieldID field_mFee { ::djinni::jniGetFieldID(clazz.get(), "mFee", "J") };
    const jfieldID field_mStatus { ::djinni::jniGetFieldID(clazz.get(), "mStatus", "Lcom/gulden/jniunifiedbackend/TransactionStatus;") };
    const jfieldID field_mHeight { ::djinni::jniGetFieldID(clazz.get(), "mHeight", "I") };
    const jfieldID field_mBlockTime { ::djinni::jniGetFieldID(clazz.get(), "mBlockTime", "J") };
    const jfieldID field_mDepth { ::djinni::jniGetFieldID(clazz.get(), "mDepth", "I") };
    const jfieldID field_mInputs { ::djinni::jniGetFieldID(clazz.get(), "mInputs", "Ljava/util/ArrayList;") };
    const jfieldID field_mOutputs { ::djinni::jniGetFieldID(clazz.get(), "mOutputs", "Ljava/util/ArrayList;") };
};

}  // namespace djinni_generated
