// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#include "NativeBlockinfoRecord.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeBlockinfoRecord::NativeBlockinfoRecord() = default;

NativeBlockinfoRecord::~NativeBlockinfoRecord() = default;

auto NativeBlockinfoRecord::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeBlockinfoRecord>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.height)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.timestamp)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.blockhash)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeBlockinfoRecord::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 4);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeBlockinfoRecord>::get();
    return {::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mHeight)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_mTimestamp)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mBlockhash))};
}

}  // namespace djinni_generated
