// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#include "NativeWitnessEstimateInfoRecord.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeWitnessEstimateInfoRecord::NativeWitnessEstimateInfoRecord() = default;

NativeWitnessEstimateInfoRecord::~NativeWitnessEstimateInfoRecord() = default;

auto NativeWitnessEstimateInfoRecord::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeWitnessEstimateInfoRecord>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.network_weight)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.weight)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.parts)),
                                                           ::djinni::get(::djinni::F64::fromCpp(jniEnv, c.estimated_witness_probability)),
                                                           ::djinni::get(::djinni::F64::fromCpp(jniEnv, c.estimated_blocks_per_day)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.estimated_daily_earnings)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.estimated_lifetime_earnings)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeWitnessEstimateInfoRecord::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 8);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeWitnessEstimateInfoRecord>::get();
    return {::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_mNetworkWeight)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_mWeight)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_mParts)),
            ::djinni::F64::toCpp(jniEnv, jniEnv->GetDoubleField(j, data.field_mEstimatedWitnessProbability)),
            ::djinni::F64::toCpp(jniEnv, jniEnv->GetDoubleField(j, data.field_mEstimatedBlocksPerDay)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_mEstimatedDailyEarnings)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_mEstimatedLifetimeEarnings))};
}

}  // namespace djinni_generated
