// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#include "NativeWitnessAccountStatisticsRecord.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeWitnessAccountStatisticsRecord::NativeWitnessAccountStatisticsRecord() = default;

NativeWitnessAccountStatisticsRecord::~NativeWitnessAccountStatisticsRecord() = default;

auto NativeWitnessAccountStatisticsRecord::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeWitnessAccountStatisticsRecord>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.request_status)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.account_status)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.account_weight)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.account_weight_at_creation)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.account_parts)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.account_amount_locked)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.account_amount_locked_at_creation)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.network_tip_total_weight)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.network_total_weight_at_creation)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.account_initial_lock_period_in_blocks)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.account_remaining_lock_period_in_blocks)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.account_expected_witness_period_in_blocks)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.account_estimated_witness_period_in_blocks)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.account_initial_lock_creation_block_height)),
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.compounding_percent)),
                                                           ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c.is_optimal)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeWitnessAccountStatisticsRecord::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 17);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeWitnessAccountStatisticsRecord>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mRequestStatus)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mAccountStatus)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_mAccountWeight)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_mAccountWeightAtCreation)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_mAccountParts)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_mAccountAmountLocked)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_mAccountAmountLockedAtCreation)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_mNetworkTipTotalWeight)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_mNetworkTotalWeightAtCreation)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_mAccountInitialLockPeriodInBlocks)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_mAccountRemainingLockPeriodInBlocks)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_mAccountExpectedWitnessPeriodInBlocks)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_mAccountEstimatedWitnessPeriodInBlocks)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_mAccountInitialLockCreationBlockHeight)),
            ::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mCompoundingPercent)),
            ::djinni::Bool::toCpp(jniEnv, jniEnv->GetBooleanField(j, data.field_mIsOptimal))};
}

}  // namespace djinni_generated
