// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#pragma once

#include "djinni_support.hpp"
#include "input_record.hpp"

namespace djinni_generated {

class NativeInputRecord final {
public:
    using CppType = ::InputRecord;
    using JniType = jobject;

    using Boxed = NativeInputRecord;

    ~NativeInputRecord();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeInputRecord();
    friend ::djinni::JniClass<NativeInputRecord>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("unity_wallet/jniunifiedbackend/InputRecord") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)V") };
    const jfieldID field_mAddress { ::djinni::jniGetFieldID(clazz.get(), "mAddress", "Ljava/lang/String;") };
    const jfieldID field_mLabel { ::djinni::jniGetFieldID(clazz.get(), "mLabel", "Ljava/lang/String;") };
    const jfieldID field_mDesc { ::djinni::jniGetFieldID(clazz.get(), "mDesc", "Ljava/lang/String;") };
    const jfieldID field_mIsMine { ::djinni::jniGetFieldID(clazz.get(), "mIsMine", "Z") };
};

}  // namespace djinni_generated
