// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#pragma once

#include "djinni_support.hpp"
#include "i_accounts_controller.hpp"

namespace djinni_generated {

class NativeIAccountsController final : ::djinni::JniInterface<::IAccountsController, NativeIAccountsController> {
public:
    using CppType = std::shared_ptr<::IAccountsController>;
    using CppOptType = std::shared_ptr<::IAccountsController>;
    using JniType = jobject;

    using Boxed = NativeIAccountsController;

    ~NativeIAccountsController();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeIAccountsController>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeIAccountsController>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeIAccountsController();
    friend ::djinni::JniClass<NativeIAccountsController>;
    friend ::djinni::JniInterface<::IAccountsController, NativeIAccountsController>;

};

}  // namespace djinni_generated
