// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#include "NativeUriRecipient.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeUriRecipient::NativeUriRecipient() = default;

NativeUriRecipient::~NativeUriRecipient() = default;

auto NativeUriRecipient::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeUriRecipient>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::Bool::fromCpp(jniEnv, c.valid)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.address)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.label)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.amount)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeUriRecipient::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 5);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeUriRecipient>::get();
    return {::djinni::Bool::toCpp(jniEnv, jniEnv->GetBooleanField(j, data.field_mValid)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mAddress)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mLabel)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mAmount))};
}

}  // namespace djinni_generated
