// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#pragma once

#include "djinni_support.hpp"
#include "gulden_unified_frontend.hpp"

namespace djinni_generated {

class NativeGuldenUnifiedFrontend final : ::djinni::JniInterface<::GuldenUnifiedFrontend, NativeGuldenUnifiedFrontend> {
public:
    using CppType = std::shared_ptr<::GuldenUnifiedFrontend>;
    using CppOptType = std::shared_ptr<::GuldenUnifiedFrontend>;
    using JniType = jobject;

    using Boxed = NativeGuldenUnifiedFrontend;

    ~NativeGuldenUnifiedFrontend();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeGuldenUnifiedFrontend>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeGuldenUnifiedFrontend>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeGuldenUnifiedFrontend();
    friend ::djinni::JniClass<NativeGuldenUnifiedFrontend>;
    friend ::djinni::JniInterface<::GuldenUnifiedFrontend, NativeGuldenUnifiedFrontend>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::GuldenUnifiedFrontend
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        bool notifySPVProgress(int32_t start_height, int32_t progess_height, int32_t expected_height) override;
        bool notifyBalanceChange(const ::BalanceRecord & new_balance) override;

    private:
        friend ::djinni::JniInterface<::GuldenUnifiedFrontend, ::djinni_generated::NativeGuldenUnifiedFrontend>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/gulden/jniunifiedbackend/GuldenUnifiedFrontend") };
    const jmethodID method_notifySPVProgress { ::djinni::jniGetMethodID(clazz.get(), "notifySPVProgress", "(III)Z") };
    const jmethodID method_notifyBalanceChange { ::djinni::jniGetMethodID(clazz.get(), "notifyBalanceChange", "(Lcom/gulden/jniunifiedbackend/BalanceRecord;)Z") };
};

}  // namespace djinni_generated
