// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#pragma once

#include "djinni_support.hpp"
#include "uri_recipient.hpp"

namespace djinni_generated {

class NativeUriRecipient final {
public:
    using CppType = ::UriRecipient;
    using JniType = jobject;

    using Boxed = NativeUriRecipient;

    ~NativeUriRecipient();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeUriRecipient();
    friend ::djinni::JniClass<NativeUriRecipient>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/gulden/jniunifiedbackend/UriRecipient") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(ZLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)V") };
    const jfieldID field_mValid { ::djinni::jniGetFieldID(clazz.get(), "mValid", "Z") };
    const jfieldID field_mAddress { ::djinni::jniGetFieldID(clazz.get(), "mAddress", "Ljava/lang/String;") };
    const jfieldID field_mLabel { ::djinni::jniGetFieldID(clazz.get(), "mLabel", "Ljava/lang/String;") };
    const jfieldID field_mAmount { ::djinni::jniGetFieldID(clazz.get(), "mAmount", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
