// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#pragma once

#include "djinni_support.hpp"
#include "wallet_lock_status.hpp"

namespace djinni_generated {

class NativeWalletLockStatus final {
public:
    using CppType = ::WalletLockStatus;
    using JniType = jobject;

    using Boxed = NativeWalletLockStatus;

    ~NativeWalletLockStatus();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeWalletLockStatus();
    friend ::djinni::JniClass<NativeWalletLockStatus>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("unity_wallet/jniunifiedbackend/WalletLockStatus") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(ZJ)V") };
    const jfieldID field_mLocked { ::djinni::jniGetFieldID(clazz.get(), "mLocked", "Z") };
    const jfieldID field_mLockTimeout { ::djinni::jniGetFieldID(clazz.get(), "mLockTimeout", "J") };
};

}  // namespace djinni_generated
