// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#pragma once

#include "djinni_support.hpp"
#include "transaction_record.hpp"

namespace djinni_generated {

class NativeTransactionRecord final {
public:
    using CppType = ::TransactionRecord;
    using JniType = jobject;

    using Boxed = NativeTransactionRecord;

    ~NativeTransactionRecord();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeTransactionRecord();
    friend ::djinni::JniClass<NativeTransactionRecord>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/gulden/jniunifiedbackend/TransactionRecord") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;JJJLjava/util/ArrayList;Ljava/util/ArrayList;)V") };
    const jfieldID field_mTxHash { ::djinni::jniGetFieldID(clazz.get(), "mTxHash", "Ljava/lang/String;") };
    const jfieldID field_mTimestamp { ::djinni::jniGetFieldID(clazz.get(), "mTimestamp", "J") };
    const jfieldID field_mAmount { ::djinni::jniGetFieldID(clazz.get(), "mAmount", "J") };
    const jfieldID field_mFee { ::djinni::jniGetFieldID(clazz.get(), "mFee", "J") };
    const jfieldID field_mReceivedOutputs { ::djinni::jniGetFieldID(clazz.get(), "mReceivedOutputs", "Ljava/util/ArrayList;") };
    const jfieldID field_mSentOutputs { ::djinni::jniGetFieldID(clazz.get(), "mSentOutputs", "Ljava/util/ArrayList;") };
};

}  // namespace djinni_generated
