// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#pragma once

#include <string>
#include <utility>

struct AccountRecord final {
    std::string UUID;
    std::string label;
    std::string state;
    std::string type;
    /**Is this account 'HD' (i.e. part of what can be recovered from a recovery phrase) */
    bool isHD;

    AccountRecord(std::string UUID_,
                  std::string label_,
                  std::string state_,
                  std::string type_,
                  bool isHD_)
    : UUID(std::move(UUID_))
    , label(std::move(label_))
    , state(std::move(state_))
    , type(std::move(type_))
    , isHD(std::move(isHD_))
    {}
};
