// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#pragma once

#include <cstdint>
#include <string>
#include <utility>

struct BlockinfoRecord final {
    int32_t height;
    int64_t timestamp;
    std::string blockhash;

    BlockinfoRecord(int32_t height_,
                    int64_t timestamp_,
                    std::string blockhash_)
    : height(std::move(height_))
    , timestamp(std::move(timestamp_))
    , blockhash(std::move(blockhash_))
    {}
};
