// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#pragma once

#include <cstdint>

struct BalanceRecord;

/** This interface will be implemented in Java and ObjC and can be called from C++. */
class GuldenUnifiedFrontend {
public:
    virtual ~GuldenUnifiedFrontend() {}

    virtual bool notifySPVProgress(int32_t start_height, int32_t progess_height, int32_t expected_height) = 0;

    virtual bool notifyBalanceChange(const BalanceRecord & new_balance) = 0;
};
