// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#include "gulden_unified_backend.hpp"  // my header
#include "qrcode_record.hpp"
#include "transaction_record.hpp"
#include "uri_recipient.hpp"
#include "uri_record.hpp"

int32_t constexpr GuldenUnifiedBackend::VERSION;
