// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#pragma once

#include <string>

struct BalanceRecord;
struct MutationRecord;
struct TransactionRecord;

/** This interface will be implemented in Java and ObjC and can be called from C++. */
class GuldenUnifiedFrontend {
public:
    virtual ~GuldenUnifiedFrontend() {}

    /**
     * Fraction of work done since session start or last progress reset [0..1]
     * Unified progress combines connection state, header and block sync
     */
    virtual void notifyUnifiedProgress(float progress) = 0;

    virtual bool notifyBalanceChange(const BalanceRecord & new_balance) = 0;

    virtual void notifyNewMutation(const MutationRecord & mutation) = 0;

    virtual bool notifyUpdatedTransaction(const TransactionRecord & transaction) = 0;

    virtual void notifyInitWithExistingWallet() = 0;

    virtual void notifyInitWithoutExistingWallet() = 0;

    virtual bool notifyShutdown() = 0;

    virtual bool notifyCoreReady() = 0;

    virtual void logPrint(const std::string & str) = 0;
};
