// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#pragma once

#include <cstdint>

/** Monitoring events */
class GuldenMonitorListener {
public:
    virtual ~GuldenMonitorListener() {}

    virtual void onPartialChain(int32_t height, int32_t probable_height, int32_t offset) = 0;

    virtual void onPruned(int32_t height) = 0;

    virtual void onProcessedSPVBlocks(int32_t height) = 0;
};
