// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#pragma once

#include <string>
#include <unordered_map>

/** C++ interface to control witness accounts */
class IWitnessController {
public:
    virtual ~IWitnessController() {}

    static std::unordered_map<std::string, std::string> getNetworkLimits();
};
