// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#pragma once

#include "transaction_record.hpp"
#include <cstdint>
#include <utility>

struct MutationRecord final {
    int64_t change;
    TransactionRecord tx;

    MutationRecord(int64_t change_,
                   TransactionRecord tx_)
    : change(std::move(change_))
    , tx(std::move(tx_))
    {}
};
