// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#pragma once

#include "output_record.hpp"
#include "transaction_status.hpp"
#include <cstdint>
#include <string>
#include <utility>
#include <vector>

struct TransactionRecord final {
    std::string txHash;
    int64_t timeStamp;
    int64_t amount;
    int64_t fee;
    TransactionStatus status;
    int32_t height;
    int64_t blockTime;
    int32_t depth;
    std::vector<OutputRecord> inputs;
    std::vector<OutputRecord> outputs;

    TransactionRecord(std::string txHash_,
                      int64_t timeStamp_,
                      int64_t amount_,
                      int64_t fee_,
                      TransactionStatus status_,
                      int32_t height_,
                      int64_t blockTime_,
                      int32_t depth_,
                      std::vector<OutputRecord> inputs_,
                      std::vector<OutputRecord> outputs_)
    : txHash(std::move(txHash_))
    , timeStamp(std::move(timeStamp_))
    , amount(std::move(amount_))
    , fee(std::move(fee_))
    , status(std::move(status_))
    , height(std::move(height_))
    , blockTime(std::move(blockTime_))
    , depth(std::move(depth_))
    , inputs(std::move(inputs_))
    , outputs(std::move(outputs_))
    {}
};
