// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#pragma once

#include "output_record.hpp"
#include <cstdint>
#include <string>
#include <utility>
#include <vector>

struct TransactionRecord final {
    std::string txHash;
    int64_t timestamp;
    int64_t amount;
    int64_t fee;
    std::vector<OutputRecord> receivedOutputs;
    std::vector<OutputRecord> sentOutputs;

    TransactionRecord(std::string txHash_,
                      int64_t timestamp_,
                      int64_t amount_,
                      int64_t fee_,
                      std::vector<OutputRecord> receivedOutputs_,
                      std::vector<OutputRecord> sentOutputs_)
    : txHash(std::move(txHash_))
    , timestamp(std::move(timestamp_))
    , amount(std::move(amount_))
    , fee(std::move(fee_))
    , receivedOutputs(std::move(receivedOutputs_))
    , sentOutputs(std::move(sentOutputs_))
    {}
};
