.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. guldencoin_qt test_guldencoin_qt
clean: FORCE
	$(MAKE) -C .. guldencoin_qt_clean test_guldencoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_guldencoin_qt_check
guldencoin-qt guldencoin-qt.exe: FORCE
	 $(MAKE) -C .. guldencoin_qt
