// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

package unity_wallet.jniunifiedbackend;

public final class AccountRecord {


    /*package*/ final String mUUID;

    /*package*/ final String mLabel;

    /*package*/ final String mState;

    /*package*/ final String mType;

    /*package*/ final boolean mIsHD;

    public AccountRecord(
            String UUID,
            String label,
            String state,
            String type,
            boolean isHD) {
        this.mUUID = UUID;
        this.mLabel = label;
        this.mState = state;
        this.mType = type;
        this.mIsHD = isHD;
    }

    public String getUUID() {
        return mUUID;
    }

    public String getLabel() {
        return mLabel;
    }

    public String getState() {
        return mState;
    }

    public String getType() {
        return mType;
    }

    /**Is this account 'HD' (i.e. part of what can be recovered from a recovery phrase) */
    public boolean getIsHD() {
        return mIsHD;
    }

    @Override
    public String toString() {
        return "AccountRecord{" +
                "mUUID=" + mUUID +
                "," + "mLabel=" + mLabel +
                "," + "mState=" + mState +
                "," + "mType=" + mType +
                "," + "mIsHD=" + mIsHD +
        "}";
    }

}
