// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

package unity_wallet.jniunifiedbackend;

public final class InputRecord implements android.os.Parcelable {


    /*package*/ final String mAddress;

    /*package*/ final String mLabel;

    /*package*/ final String mDesc;

    /*package*/ final boolean mIsMine;

    public InputRecord(
            String address,
            String label,
            String desc,
            boolean isMine) {
        this.mAddress = address;
        this.mLabel = label;
        this.mDesc = desc;
        this.mIsMine = isMine;
    }

    public String getAddress() {
        return mAddress;
    }

    public String getLabel() {
        return mLabel;
    }

    public String getDesc() {
        return mDesc;
    }

    public boolean getIsMine() {
        return mIsMine;
    }

    @Override
    public String toString() {
        return "InputRecord{" +
                "mAddress=" + mAddress +
                "," + "mLabel=" + mLabel +
                "," + "mDesc=" + mDesc +
                "," + "mIsMine=" + mIsMine +
        "}";
    }


    public static final android.os.Parcelable.Creator<InputRecord> CREATOR
        = new android.os.Parcelable.Creator<InputRecord>() {
        @Override
        public InputRecord createFromParcel(android.os.Parcel in) {
            return new InputRecord(in);
        }

        @Override
        public InputRecord[] newArray(int size) {
            return new InputRecord[size];
        }
    };

    public InputRecord(android.os.Parcel in) {
        this.mAddress = in.readString();
        this.mLabel = in.readString();
        this.mDesc = in.readString();
        this.mIsMine = in.readByte() != 0;
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(android.os.Parcel out, int flags) {
        out.writeString(this.mAddress);
        out.writeString(this.mLabel);
        out.writeString(this.mDesc);
        out.writeByte(this.mIsMine ? (byte)1 : 0);
    }

}
