// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

package unity_wallet.jniunifiedbackend;

public enum PaymentResultStatus {
    SUCCESS,
    INSUFFICIENT_FUNDS,
}
