// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

package unity_wallet.jniunifiedbackend;

/**
 * Copyright (c) 2018-2022 The Centure developers
 * Authored by: Malcolm MacLeod (mmacleod@gmx.com)
 * Distributed under the Libre Chain License, see the accompanying
 * file COPYING
 */
public final class ResultRecord {


    /*package*/ final boolean mResult;

    /*package*/ final String mInfo;

    public ResultRecord(
            boolean result,
            String info) {
        this.mResult = result;
        this.mInfo = info;
    }

    public boolean getResult() {
        return mResult;
    }

    public String getInfo() {
        return mInfo;
    }

    @Override
    public String toString() {
        return "ResultRecord{" +
                "mResult=" + mResult +
                "," + "mInfo=" + mInfo +
        "}";
    }

}
