// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

package unity_wallet.jniunifiedbackend;

public enum TransactionStatus {
    UNCONFIRMED,
    CONFIRMING,
    CONFIRMED,
    ABANDONED,
    CONFLICTED,
}
