// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#ifndef DJINNI_GENERATED_NJSIRPCCONTROLLER_HPP
#define DJINNI_GENERATED_NJSIRPCCONTROLLER_HPP


#include "NJSIRpcListener.hpp"
#include <memory>
#include <string>
#include <vector>

#include <napi.h>
#include <uv.h>
#include <i_rpc_controller.hpp>

using namespace std;

class NJSIRpcController: public Napi::ObjectWrap<NJSIRpcController> {
public:

    static Napi::FunctionReference constructor;
    static Napi::Object Init(Napi::Env env, Napi::Object exports);
    NJSIRpcController(const Napi::CallbackInfo& info) : Napi::ObjectWrap<NJSIRpcController>(info){};

private:
    void execute(const Napi::CallbackInfo& info);

    Napi::Value getAutocompleteList(const Napi::CallbackInfo& info);

};
#endif //DJINNI_GENERATED_NJSIRPCCONTROLLER_HPP
