// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

#ifndef DJINNI_GENERATED_NJSIGENERATIONLISTENER_HPP
#define DJINNI_GENERATED_NJSIGENERATIONLISTENER_HPP


#include <string>

#include <napi.h>
#include <uv.h>
#include <i_generation_listener.hpp>

using namespace std;

class NJSIGenerationListener: public Napi::ObjectWrap<NJSIGenerationListener> {
public:

    static Napi::FunctionReference constructor;
    static Napi::Object Init(Napi::Env env, Napi::Object exports);
    NJSIGenerationListener(const Napi::CallbackInfo& info) : Napi::ObjectWrap<NJSIGenerationListener>(info){};

    /** Signal that block generation has started */
    void onGenerationStarted();

    /** Signal that block generation has stopped */
    void onGenerationStopped();

    /** Periodically signal latest block generation statistics */
    void onStatsUpdated(double hashesPerSecond, const std::string & hashesPerSecondUnit, double rollingHashesPerSecond, const std::string & rollingHashesPerSecondUnit, double bestHashesPerSecond, const std::string & bestHashesPerSecondUnit, double arenaSetupTime);

private:
    /** Signal that block generation has started */
    void onGenerationStarted(const Napi::CallbackInfo& info);
    void onGenerationStarted_aimpl__();

    /** Signal that block generation has stopped */
    void onGenerationStopped(const Napi::CallbackInfo& info);
    void onGenerationStopped_aimpl__();

    /** Periodically signal latest block generation statistics */
    void onStatsUpdated(const Napi::CallbackInfo& info);
    void onStatsUpdated_aimpl__(double hashesPerSecond, const std::string & hashesPerSecondUnit, double rollingHashesPerSecond, const std::string & rollingHashesPerSecondUnit, double bestHashesPerSecond, const std::string & bestHashesPerSecondUnit, double arenaSetupTime);

};
#endif //DJINNI_GENERATED_NJSIGENERATIONLISTENER_HPP
