// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

package com.novo.jniunifiedbackend;

/**
 * Copyright (c) 2018-2020 The Novo developers
 * Authored by: Malcolm MacLeod (mmacleod@gmx.com)
 * Distributed under the Novo software license, see the accompanying
 * file COPYING
 */
public final class QrCodeRecord {


    /*package*/ final int mWidth;

    /*package*/ final byte[] mPixelData;

    public QrCodeRecord(
            int width,
            byte[] pixelData) {
        this.mWidth = width;
        this.mPixelData = pixelData;
    }

    public int getWidth() {
        return mWidth;
    }

    public byte[] getPixelData() {
        return mPixelData;
    }

    @Override
    public String toString() {
        return "QrCodeRecord{" +
                "mWidth=" + mWidth +
                "," + "mPixelData=" + mPixelData +
        "}";
    }

}
