// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from libunity.djinni

package com.novo.jniunifiedbackend;

public enum TransactionStatus {
    UNCONFIRMED,
    CONFIRMING,
    CONFIRMED,
    ABANDONED,
    CONFLICTED,
    ;
}
